version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DEBUG=true
    env_file:
      - .env
    volumes:
      - ./:/app
    command: uv run uvicorn main:app --host 0.0.0.0 --port 8000 --reload