apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-task-manager
  labels:
    app: ai-task-manager
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ai-task-manager
  template:
    metadata:
      labels:
        app: ai-task-manager
    spec:
      containers:
      - name: ai-task-manager
        image: gcr.io/your-gcp-project-id/ai-task-manager:latest
        ports:
        - containerPort: 8000
        env:
        - name: GOOGLE_API_KEY
          valueFrom:
            secretKeyRef:
              name: api-secrets
              key: google-api-key
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
            nvidia.com/gpu: 1
          limits:
            memory: "512Mi"
            cpu: "500m"
            nvidia.com/gpu: 1
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
      nodeSelector:
        accelerator: nvidia-tesla-l4

---
apiVersion: v1
kind: Service
metadata:
  name: ai-task-manager-service
spec:
  selector:
    app: ai-task-manager
  ports:
  - port: 80
    targetPort: 8000
  type: LoadBalancer